services:
  eth-firehose:
    image: eth-firehose
    build:
      context: .
      dockerfile: ./dockerfiles/eth-firehose-node.Dockerfile
    ports:
      - "10015:10015"
      - "10016:10016"
      - "9545:9545"
      - "9546:9546"
      - "7060:7060"
      - "9551:9551"
      - "30304:30304/tcp"
      - "30304:30304/udp"
    env_file:
      - ./localnet/config/values.env
    volumes:
      - ./localnet/nodes/node2/execution-data:/execution-data
      - ./localnet/el-cl-genesis-data:/el-cl-genesis-data
      - ./localnet/firehose:/firehose
    networks:
      localnet:
        ipv4_address: 172.19.0.111
    extra_hosts:
      - "host.docker.internal:host-gateway"

  firehose-beacon:
    image: firehose-beacon
    build:
      context: .
      dockerfile: ./dockerfiles/eth-firehose-beacon.Dockerfile
    environment:
      - EL_NODE_ENDPOINTS=http://eth-firehose:8545
      - LOCALNET_NODE_IP=172.19.0.121
      - CL_CHECKPOINT=http://host.docker.internal:5052
    volumes:
      - ./localnet/nodes/node2/consensus-data:/consensus-data
      - ./localnet/el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "10000:10000/tcp"
      - "10000:10000/udp"
      - "10001:10001/udp"
      - "6052:6052"
      - "6054:6054"
    depends_on:
      - eth-firehose
    restart: unless-stopped
    networks:
      localnet:
        ipv4_address: 172.19.0.121
    extra_hosts:
      - "host.docker.internal:host-gateway"

  eth-setup:
    image: "eth-setup"
    build:
      context: .
      dockerfile: ./dockerfiles/ethereum-setup.Dockerfile
    command:
      - "--chain-id=31337"
      - "--url=http://host.docker.internal:8545"
      - "--private-key=f6299cb9ba7c7168a00286d341f381a312d46964ad961d67ebe5426767357c51" #--dev private key
    # This is a one shot service
    restart: "no"
    stdin_open: false
    networks:
      localnet:
        ipv4_address: 172.19.0.123
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  localnet:
    external: true
