services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      # Required by pg_isready
      - PGUSER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=node
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 1s

  signer:
    image: "signer"
    restart: always
    environment:
      - ROOT_KEY=tprv8ZgxMBicQKsPeb6rodrmEXb1zRucvxYJgTKDhqQkZtbz8eY4Pf2EgbsT2swBXnnbDPQChQeFrFqHN72yFxzKfFAVsHdPeRWq2xqyUT2c4wH
      - SOCKET_PORT=10001
    ports:
      - "10001:10001"
    build:
      context: .
      dockerfile: ./dockerfiles/signer.Dockerfile
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:10001"]
      start_period: 1s

  node:
    image: "node"
    restart: always
    environment:
      - PG_URL=postgres://postgres:password@db/node
      - SIGNER_URL=http://signer:10001
      - GRPC_IP=[::0]
      - GRPC_PORT=20001
    ports:
      - "20001:20001"
    build:
      context: .
      dockerfile: ./dockerfiles/node.Dockerfile
    depends_on:
      db:
        condition: service_healthy
      signer:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "20001"]
      start_period: 3s

volumes:
  database_data:
    driver: local
