services:
  eth-devnet:
    image: "ghcr.io/streamingfast/go-ethereum:geth-v1.16.1-fh3.0-2"
    entrypoint: [geth]
    command:
      - --dev
      - --dev.period=3
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,debug,admin
      - --http.corsdomain=*
      - --http.vhosts=*
      - --ws 
      - --ws.addr=0.0.0.0 
      - --ws.port=8546 
      - --ws.api=web3,eth,net,admin,debug
    ports:
     - "8545:8545"
     - "8546:8546" 
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:8545"]
      start_period: 1s
      interval: 5s
      timeout: 15s
      retries: 5