services:
  localnet-genesis:
    image: localnet-genesis
    build:
      context: .
      dockerfile: ./dockerfiles/localnet-node-genesis.Dockerfile
    container_name: localnet-genesis
    volumes:
      - ./localnet/el-cl-genesis-data:/data
      - ./localnet/config:/config
      - ./localnet/nodes:/nodes
    restart: "no"
