// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BlockMeta {
    #[prost(uint64, tag="2")]
    pub height: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PaymentEvent {
    #[prost(uint64, tag="2")]
    pub index: u64,
    #[prost(string, tag="3")]
    pub payee: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub asset: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub invoice_id: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub payer: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub amount_low: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub amount_high: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<PaymentEvent>,
}
// @@protoc_insertion_point(module)
