[package]
name = "starknet-invoice-substream"
version = "0.1.0"
edition = "2024"

[lib]
name = "starknet_invoice_substream"
crate-type = ["cdylib"]

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
substreams = "0.6.0"
anyhow = { workspace = true }
