[package]
name = "tls"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = { version = "0.9", features = ["tls"] }
tokio = { version = "1", features = ["full"] }
anyhow = { workspace = true }
tonic-build = "0.9"