[package]
name = "invoice_payment"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.12.0"
openzeppelin_token = "2.0.0"
openzeppelin_presets = "2.0.0"
openzeppelin_utils = "2.0.0"

[dev-dependencies]
snforge_std = "0.47.0"
assert_macros = "2.9.2"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "audited"
build-external-contracts = ["openzeppelin_presets::erc20::ERC20Upgradeable"]

[scripts]
test = "snforge test"

[profile.dev.cairo]                                        # Configure Cairo compiler
unstable-add-statements-code-locations-debug-info = true   # Should be used if you want to use coverage
unstable-add-statements-functions-debug-info = true        # Should be used if you want to use coverage/profiler
inlining-strategy = "avoid"                                # Should be used if you want to use coverage
