services:
  ethereum-devnet:
    build:
      context: ..
      dockerfile: dockerfiles/ethereum-setup.Dockerfile
    restart: always
    ports:
      - "8545:8545"  # HTTP RPC
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80  # First Anvil account
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8545 -X POST -H 'Content-Type: application/json' --data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}' || exit 1"]
      start_period: 10s
      interval: 5s
      retries: 5