services:
  ethereum-devnet:
    image: "ghcr.io/foundry-rs/foundry:latest"
    restart: always
    command:
      - anvil
      - --host=0.0.0.0
      - --port=8545
      - --chain-id=1337
      - --accounts=10
      - --balance=10000
      - --gas-limit=30000000
      - --gas-price=1000000000
      - --block-time=2
    ports:
      - "8545:8545"  # HTTP RPC
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8545 -X POST -H 'Content-Type: application/json' --data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}' || exit 1"]
      start_period: 5s
      interval: 5s
      retries: 5