services:
  starknet-devnet:
    image: "docker.io/shardlabs/starknet-devnet-rs:0.4.3"
    environment:
      - SEED=0
      - BLOCK_GENERATION_ON=${BLOCK_TIME:-1}
      - CHAIN_ID=SN_DEVNET
    ports:
      - "5050:5050"
    restart: always
    healthcheck:
      # Doing http calls without having to install curl or wget
      # https://github.com/dart-lang/dart-docker/issues/58#issuecomment-1410663799
      test: ["CMD", "bash", "-c", 'exec 3<>/dev/tcp/localhost/5050;echo -e "GET /is_alive HTTP/1.1\r\nHost: localhost:5050\r\nConnection: close\r\n\r\n" >&3; grep "200 OK" <&3']
      start_period: 1s
      interval: 3s
      retries: 3

  block-fetcher:
    image: curlimages/curl:latest
    user: root
    volumes:
      - starknet-network-data:/shared
    command: >
     sh -c "
        echo 'Fetching fork block number and chain ID from devnet config...' &&
        CONFIG_JSON=$$(curl -s http://starknet-devnet:5050/config) &&
        CHAIN_ID=$$(echo \"$$CONFIG_JSON\" | \
          grep -o '\"chain_id\":\"[^\"]*\"' | \
          cut -d'\"' -f4) &&
        if [ -n \"$$CHAIN_ID\" ]; then
          echo $$CHAIN_ID > /shared/chain_id.txt &&
          echo 'Chain ID: '$$CHAIN_ID
        else
          echo 'ERROR: failed to fetch chain ID' >&2 &&
          exit 1
        fi
      "
    depends_on:
      starknet-devnet:
        condition: service_healthy

  starknet-firehose:
    image: starknet-firehose
    build:
      context: ..
      dockerfile: ./dockerfiles/starknet-firehose.Dockerfile
    environment:
      - LATEST_BLOCK_RETRY_INTERVAL=${BLOCK_TIME:-1}s
      - BLOCK_FETCH_BATCH_SIZE=20
      - ADVERTISE_CHAIN_NAME=devnet
    ports:
      - "10015:10015"
      - "10016:10016"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:10001"]
      start_period: 1s
      interval: 3s
      retries: 3
    depends_on:
      starknet-devnet:
        condition: service_healthy
      block-fetcher:
        condition: service_completed_successfully

  explorer:
    image: "explorer"
    restart: always
    ports:
      - "3004:3004"
    build:
      context: ..
      dockerfile: ./dockerfiles/explorer.Dockerfile
    environment:
      # Use localhost here because it has to be the address from the browser POV, not from the server
      - VITE_RPC_URL=http://localhost:5050
      - VITE_IS_EMBEDDED=false
      - VITE_CHAIN_ID=SN_DEVNET
    depends_on:
      starknet-devnet:
        condition: service_healthy

  starknet-setup:
    image: "starknet-setup"
    build:
      context: ..
      dockerfile: ./dockerfiles/starknet-setup.Dockerfile
    command:
      - "--chain-id=SN_DEVNET"
      - "--url=http://starknet-devnet:5050"
      - "--private-key=0x0000000000000000000000000000000071d7bb07b9a64f6f78ac4c816aff4da9"
      - "--account-address=0x064b48806902a367c8598f4f95c305e8c1a1acba5f082d294a43793113115691"
    depends_on:
      starknet-devnet:
        condition: service_healthy

volumes:
  starknet-network-data:
