// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemittanceEvents {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<RemittanceEvent>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemittanceEvent {
    #[prost(string, tag = "1")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub log_index: u32,
    #[prost(string, tag = "3")]
    pub asset: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub payee: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub invoice_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub payer: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub amount: ::prost::alloc::string::String,
}
