name: Code Quality
on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove unwanted files
        run: rm -f rust-toolchain.toml
      - uses: dtolnay/rust-toolchain@1.86.0
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Check clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove unwanted files
        run: rm -f rust-toolchain.toml
      - uses: dtolnay/rust-toolchain@1.86.0
        with:
          components: clippy
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: "28.x"
      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libdbus-1-dev pkg-config
          version: 1.0
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: rust-cache-clippy-${{ hashFiles('Cargo.lock') }}
          cache-on-failure: true
          cache-all-crates: true
      - name: Run clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings --no-deps

  mobile-fmt:
    name: Check Formatting (mobile)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove unwanted files
        run: rm -f rust-toolchain.toml
      - uses: dtolnay/rust-toolchain@1.86.0
        with:
          components: rustfmt
      - name: Check formatting
        working-directory: mobile
        run: cargo fmt --all -- --check

  movile-clippy:
    name: Check clippy (mobile)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4
      - name: Remove unwanted files
        run: rm -f rust-toolchain.toml

      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev
          version: 1.0
      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libdbus-1-dev pkg-config
          version: 1.0

      - uses: dtolnay/rust-toolchain@1.86.0
        with:
          components: clippy
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: "28.x"

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: rust-mobile-clippy-${{ hashFiles('mobile/Cargo.lock') }}
          cache-on-failure: true
          cache-all-crates: true
      - name: Create fake certificate
        working-directory: mobile/salto
        run: |
          mkdir src-tauri/certs
          touch src-tauri/certs/rootCA.pem
      - name: Run clippy
        working-directory: mobile
        env:
          PRICE_PROVIDER_URL: "http://localhost:80"
          WEB_APP_URL: "https://localhost:3005"
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings --no-deps

  
