services:
# Mint
  signer:
    image: "ghcr.io/nutty-raccoon/paynet-signer:${SIGNER_VERSION}"
    restart: always
    environment:
      - ROOT_KEY
      - GRPC_PORT=10001
      # Open telemetry
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=signer
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:10001"]
      start_period: 1s
      interval: 3s
      retries: 3

  node:
    image: "ghcr.io/nutty-raccoon/paynet-node:${NODE_VERSION}"
    restart: always
    environment:
      - PG_URL
      - SIGNER_URL=http://signer:10001
      - GRPC_PORT=10003
      # Open telemetry
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=node
      # Starknet
      - STARKNET_CASHIER_ACCOUNT_ADDRESS
      - STARKNET_CASHIER_PRIVATE_KEY
      - STARKNET_RPC_NODE_URL=https://starknet-sepolia.public.blastapi.io/rpc/v0_8
      - STARKNET_SUBSTREAMS_URL=https://testnet.starknet.streamingfast.io:443
    depends_on:
      signer:
        condition: service_healthy
      otel-collector:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:10003"]
      start_period: 1s
      interval: 3s
      retries: 3

# Open telemetry
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "8888:8888"  
      - "8889:8889"  
      - "13133:13133"  
    volumes:
      - ./observability/docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    restart: always
    depends_on:
      prometheus:
        condition: service_started
      jaeger:
        condition: service_started
      loki:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:13133/"]
      interval: 5s
      timeout: 2s
      retries: 3

# nginx
  nginx:
    image: nginx:latest
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ./node-starknet-sepolia.nginx.conf:/etc/nginx/templates/default.conf.template
      - ${TLS_CERT_PATH}:/etc/nginx/ssl/cert.pem
      - ${TLS_KEY_PATH}:/etc/nginx/ssl/key.pem
    ports:
      - "80:80"     # Add this for HTTP -> HTTPS redirects
      - "443:443"
    depends_on:
      node:
        condition: service_healthy
