services:
# Mint
  signer:
    image: "ghcr.io/nutty-raccoon/paynet-signer:${SIGNER_VERSION-latest}"
    restart: always
    environment:
      - ROOT_KEY
      - GRPC_PORT=10001
      # Open telemetry
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=signer
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:10001"]
      start_period: 1s
      interval: 3s
      retries: 3

  node:
    image: "ghcr.io/nutty-raccoon/paynet-node:${NODE_VERSION-latest}"
    restart: always
    environment:
      - PG_URL
      - SIGNER_URL=http://signer:10001
      - GRPC_PORT=10003
      # Open telemetry
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=node
      # Starknet
      - STARKNET_CASHIER_ACCOUNT_ADDRESS
      - STARKNET_CASHIER_PRIVATE_KEY
      - STARKNET_RPC_NODE_URL=https://starknet-sepolia.public.blastapi.io/rpc/v0_8
      - STARKNET_SUBSTREAMS_URL=https://testnet.starknet.streamingfast.io:443
    depends_on:
      signer:
        condition: service_healthy
      otel-collector:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:10003"]
      start_period: 1s
      interval: 3s
      retries: 3

# Open telemetry
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.135.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "8888:8888"  
      - "8889:8889"  
      - "13133:13133"  
    volumes:
      - ../../observability/docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:13133/"]
      interval: 5s
      timeout: 2s
      retries: 3

# nginx
  nginx:
    image: nginx:1.29-alpine
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./node-starknet-sepolia.nginx.conf:/etc/nginx/templates/default.conf.template
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c '/docker-entrypoint.d/20-envsubst-on-templates.sh && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"


  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

