[package]
name = "starknet-cashier"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tonic = { workspace = true }
tonic-types = { workspace = true }
tonic-health = { workspace = true }
dotenvy = { workspace = true }
anyhow = { workspace = true }
starknet = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

# Local deps
starknet-types = { workspace = true }

[features]

[build-dependencies]
tonic-build = "0.13.0"

