name: iOS Wallet Release

on:
  push:
    tags:
      - 'iOS-wallet-v*'
      - 'wallet-v*'

concurrency:
  group: ios-wallet-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-latest
    outputs:
      version_string: ${{ steps.app-version.outputs.version_string }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CocoaPods
        run: |
          sudo gem install cocoapods
          pod --version

      - name: setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@1.86.0
        with:
          targets: aarch64-apple-ios,x86_64-apple-ios,aarch64-apple-ios-sim

      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: "28.x"

      - name: install bun dependencies
        working-directory: mobile/salto
        run: bun install --frozen-lockfile

      - name: restore Rust cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            mobile/target/
          key: ${{ runner.os }}-ios-wallet-${{ hashFiles('mobile/Cargo.lock') }}-${{ hashFiles('mobile/salto/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-ios-wallet-${{ hashFiles('mobile/Cargo.lock') }}
            ${{ runner.os }}-ios-wallet-

      - name: Build iOS app
        working-directory: mobile/salto
        run: bun tauri ios build --export-method app-store-connect
        env:
          PRICE_PROVIDER_URL: https://price-provider.mobile.tdelabro.com
          WEB_APP_URL: https://invoice-payment.tdelabro.com
          # ios signing
          IOS_MOBILE_PROVISION: ${{ secrets.IOS_MOBILE_PROVISION }}
          IOS_CERTIFICATE: ${{ secrets.APPSTORE_DISTRIBUTION_CERTIFICATES_FILE_BASE64 }}
          IOS_CERTIFICATE_PASSWORD: ${{ secrets.APPSTORE_DISTRIBUTION_CERTIFICATES_PASSWORD }}

      - name: Get Tauri App Version
        working-directory: mobile/salto
        id: app-version
        run: |
          CARGO_TOML_PATH="src-tauri/Cargo.toml"
          echo "Attempting to read version from $CARGO_TOML_PATH"

          if [ ! -f "$CARGO_TOML_PATH" ]; then
            echo "Error: $CARGO_TOML_PATH not found."
            exit 1
          fi

          echo "--- Relevant content from $CARGO_TOML_PATH (looking for 'version = \"...' line) ---"
          grep '^version = "' "$CARGO_TOML_PATH" || echo "No line starting with 'version = \"' found in $CARGO_TOML_PATH."
          echo "--- End of relevant content ---"

          # Extract version string from Cargo.toml.
          # This looks for a line like 'version = "x.y.z"' in the [package] section.
          VERSION_STRING=$(grep '^version = "' "$CARGO_TOML_PATH" | head -n 1 | sed -e 's/version = "//' -e 's/"//')

          echo "Extracted version_string: '$VERSION_STRING'" # Debug output

          if [ -z "$VERSION_STRING" ] || [ "$VERSION_STRING" = "null" ]; then # Check for empty or literal "null"
            echo "Error: Version not found or is invalid in $CARGO_TOML_PATH."
            echo "Please ensure $CARGO_TOML_PATH contains a line like 'version = \"x.y.z\"' (typically under the [package] section)."
            exit 1
          fi

          echo "Successfully extracted version: $VERSION_STRING"
          echo "version_string=$VERSION_STRING" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Save Rust cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            mobile/target/
          key: ${{ runner.os }}-ios-wallet-${{ hashFiles('mobile/Cargo.lock') }}-${{ hashFiles('mobile/salto/bun.lock') }}-${{ github.run_id }}

      - name: Rename IPA file
        working-directory: mobile/salto
        run: |
          mv ./src-tauri/gen/apple/build/arm64/salto.ipa ./src-tauri/gen/apple/build/arm64/salto-${{ steps.app-version.outputs.version_string }}.ipa

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-${{ steps.app-version.outputs.version_string }}
          path: './mobile/salto/src-tauri/gen/apple/build/arm64/salto-${{ steps.app-version.outputs.version_string }}.ipa'
          retention-days: 1

      - name: Cleanup keychain
        if: always()
        run: security delete-keychain build.keychain || true

  publish:
    needs: build
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ios-build-${{ needs.build.outputs.version_string }}
          path: ./

      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v3
        with: 
          app-path: './salto-${{ needs.build.outputs.version_string }}.ipa' 
          issuer-id: ${{ vars.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ vars.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
